# Se https://gohugo.io/getting-started/configuration/
# för fler inställningar i denna fil.

baseurl = "https://xicode.se"
languageCode = "en-us"
theme = "terminal"
paginate = 5
#disqusShortname = "xicode"
enableEmoji = true
enableInlineShortcodes = true

[author]
    name = "Nikodemus"       #Author name
    twitter = "magistern"

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "orange"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # set theme to full screen width
  fullWidthTheme = false
  # center theme with default width
  centerTheme = true
  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  [permalinks]
  # Se denna länk: https://gohugo.io/content-management/urls/
    posts = "/:year/:month/:title/"

[languages]
  [languages.en]
    title = "xicode.se"
    subtitle = ""
    keywords = "programmering"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "xicode.se"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 50
      #[[languages.en.menu.main]]
      #  identifier = "showcase"
      #  name = "Showcase"
      #  parent = ""
      #  url = "/showcase"
      #  weight = 100
